### /
GET {{host}}/
Accept: application/json

### /start
POST {{host}}/start
Content-Type: application/json

{
}

### /move
POST {{host}}/move
Content-Type: application/json

< ./example_move.json

### /end
POST {{host}}/end
Content-Type: application/json

{
}
