### /
GET http://127.0.0.1:8000/
Accept: application/json

### /start
POST http://127.0.0.1:8000/start
Accept: application/json

{
}

### /move
POST http://127.0.0.1:8000/move
Accept: application/json

{
}

### /end
POST http://127.0.0.1:8000/end
Accept: application/json

{
}
